// <auto-generated />
using System;
using CarRentalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalManagement.Migrations
{
    [DbContext(typeof(CarRentalManagementContext))]
    [Migration("20241118084434_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalManagement.Domain.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Colour", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Colour");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(6906),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(6923),
                            Name = "Black",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(6925),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(6925),
                            Name = "Blue",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrivingLicence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Make", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Make");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7115),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7116),
                            Name = "BMW",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7117),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7117),
                            Name = "Toyota",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Model");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7180),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7180),
                            Name = "i4",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7182),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7182),
                            Name = "X5",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7183),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7184),
                            Name = "Prius",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7185),
                            DateUpdated = new DateTime(2024, 11, 18, 16, 44, 33, 794, DateTimeKind.Local).AddTicks(7185),
                            Name = "C-HR",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarRentalManagement.Domain.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
